- name: untar to temporary location
  shell: cd /tmp/ && rm -rf {{webapp_archive_location}}.untarred && mkdir {{webapp_archive_location}}.untarred && cd {{webapp_archive_location}}.untarred && tar xzf {{webapp_archive_location}}
- synchronize: src="{{webapp_archive_location}}.untarred/" dest="{{src_root}}/"
  delegate_to: "{{ inventory_hostname }}"
- name: bootstrap
  shell: python {{src_root}}/manage.py bootstrap --app
- name: ensure private config
  shell: python {{src_root}}/manage.py ensure-secret {{deploy_root}}/conf.d/000-private.yml
- name: migrate db
  shell: cd {{src_root}} && python manage.py db upgrade
- name: fix permissions
  file: path={{deploy_root}} owner={{user_name}} group={{group_name}} recurse=true
- name: fix permissions of static folder
  file: path={{src_root}}/static owner={{nginx_user}} group={{nginx_group}} recurse=true state=directory
- name: ensure that nginx sites directory exists
  file: dest={{nginx_sites_dir}} state=directory
- name: ensure nginx configuration
  template: src=../templates/nginx_site_conf.conf.j2 dest={{nginx_sites_dir}}/{{app_name}}.conf
  register: nginx_conf
- shell: nginx -s reload
  when: nginx_conf.changed
