- name: temporarily move source tar
  shell: mv -f {{webapp_archive_location}} {{webapp_archive_location}}.untarred
- name: untar sources
  shell: cd {{deploy_root}} && rm -rf flask_app src && tar xfz {{webapp_archive_location}}.untarred 2>&1 > /tmp/untar.log
- name: bootstrap
  shell: python {{deploy_root}}/manage.py bootstrap --app
- name: ensure private config
  shell: python {{deploy_root}}/manage.py ensure-secret {{deploy_root}}/conf.d/000-private.yml
- name: migrate db
  shell: cd {{deploy_root}} && python manage.py db upgrade
- name: fix permissions
  shell: chown -R {{user_name}}:{{group_name}} {{deploy_root}}
- name: ensure nginx configuration
  shell: python {{deploy_root}}/manage.py generate_nginx_config /etc/nginx/sites-enabled/{{app_name}} {{fqdn}} {{short_name}}
  notify: reload nginx config
- name: reload supervisor
  shell: supervisorctl reload
  when: in_docker is not defined
- name: ensure supervisor service
  action: service name=supervisor state=started
  when: in_docker is not defined
- name: try to get local page
  shell: curl http://localhost/
- name: move source tar back to prevent future reinstallations
  shell: mv -f {{webapp_archive_location}}.untarred {{webapp_archive_location}}
