matrix:
  include:
    - language: python
      env:
        - MYPYPATH=stubs
      python: 3.7
      cache:
        - poetry
      install:
        - pip install poetry
      script:
        - poetry install
        - mypy flask_app/

    - language: node_js
      node_js:
        - "8"
      cache:
        - yarn

      before_install:
        - curl -o- -L https://yarnpkg.com/install.sh | bash
        - export PATH=$HOME/.yarn/bin:$PATH

      install:
        - gem install scss_lint

      script:
        - cd webapp
        - yarn install
        - yarn lint:js
        - ./node_modules/ember-cli/bin/ember build

    - language: rust
      script:
        - cd transporter
        - cargo build
