matrix:
  include:
    - language: python
      python: 3.4
      cache:
        - pip
      install:
        - pip install virtualenv
      script:
        - python3 manage.py bootstrap --app --develop

    - language: node_js
      node_js:
        - "6"
      cache:
        - yarn

      before_install:
        - curl -o- -L https://yarnpkg.com/install.sh | bash
        - export PATH=$HOME/.yarn/bin:$PATH

      install:
        - gem install scss_lint

      script:
        - cd webapp
        - yarn install
        - yarn lint:js
