 production: true
 transporter_host: "scotty"
 sentry_dsn: "http://da99721dc2e14a0bb12debb7447efb44:69007f54ceb04ca8acb85aa86c8d3db9@sentry.infinidat.com/21"
 vacuum_threshold: 90
 pin_remind_threshold: 92
 fqdn: "http://scotty.infinidat.com"
 hostname_redirect_aliases: ["scotty"]
