"""empty message

Revision ID: 14bbb53415d
Revises: 43c099bc745
Create Date: 2015-11-12 13:48:57.368126

"""

# revision identifiers, used by Alembic.
revision = '14bbb53415d'
down_revision = '43c099bc745'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('beam_type',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('vacuum_threshold', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_beam_type_name'), 'beam_type', ['name'], unique=True)
    op.add_column('beam', sa.Column('type_id', sa.Integer(), nullable=True))
    op.create_foreign_key('beam_type_fkey', 'beam', 'beam_type', ['type_id'], ['id'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('beam_type_fkey', 'beam', type_='foreignkey')
    op.drop_column('beam', 'type_id')
    op.drop_index(op.f('ix_beam_type_name'), table_name='beam_type')
    op.drop_table('beam_type')
    ### end Alembic commands ###
