"""empty message

Revision ID: 27bc2f86a2b3
Revises: b3b53fd2bce1
Create Date: 2021-01-03 13:01:57.324076

"""

# revision identifiers, used by Alembic.
revision = '27bc2f86a2b3'
down_revision = 'b3b53fd2bce1'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_issue_id_in_tracker'), 'issue', ['id_in_tracker'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_issue_id_in_tracker'), table_name='issue')
    # ### end Alembic commands ###
