"""empty message

Revision ID: 2abcb206208
Revises: e80348dc45
Create Date: 2015-04-29 13:33:02.505208

"""

# revision identifiers, used by Alembic.
revision = '2abcb206208'
down_revision = 'e80348dc45'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alias',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('beam_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['beam_id'], ['beam.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('beam', sa.Column('error', sa.String(), nullable=True))
    op.create_index(op.f('ix_beam_deleted'), 'beam', ['deleted'], unique=False)
    op.create_index(op.f('ix_beam_pending_deletion'), 'beam', ['pending_deletion'], unique=False)
    op.create_index(op.f('ix_beam_start'), 'beam', ['start'], unique=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_beam_start'), table_name='beam')
    op.drop_index(op.f('ix_beam_pending_deletion'), table_name='beam')
    op.drop_index(op.f('ix_beam_deleted'), table_name='beam')
    op.drop_column('beam', 'error')
    op.drop_table('alias')
    ### end Alembic commands ###
