"""empty message

Revision ID: 352114acb70
Revises: 699b7b4a89
Create Date: 2015-07-01 10:43:23.060333

"""

# revision identifiers, used by Alembic.
revision = '352114acb70'
down_revision = '699b7b4a89'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('beam', sa.Column('combadge_contacted', sa.Boolean(), server_default='true', nullable=False))
    op.create_index(op.f('ix_beam_completed'), 'beam', ['completed'], unique=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_beam_completed'), table_name='beam')
    op.drop_column('beam', 'combadge_contacted')
    ### end Alembic commands ###
