"""empty message

Revision ID: 364749445a7
Revises: 19d086b825c
Create Date: 2015-04-13 13:44:23.576455

"""

# revision identifiers, used by Alembic.
revision = '364749445a7'
down_revision = '19d086b825c'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('beam', sa.Column('deleted', sa.Boolean(), nullable=True))
    op.add_column('file', sa.Column('storage_name', sa.String(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('file', 'storage_name')
    op.drop_column('beam', 'deleted')
    ### end Alembic commands ###
