"""empty message

Revision ID: 3e03545a772
Revises: e3f9f9c13c
Create Date: 2015-11-04 14:39:44.329422

"""

# revision identifiers, used by Alembic.
revision = '3e03545a772'
down_revision = 'e3f9f9c13c'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_tag_beam_id'), 'tag', ['beam_id'], unique=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tag_beam_id'), table_name='tag')
    ### end Alembic commands ###
