"""empty message

Revision ID: 43c099bc745
Revises: 3e03545a772
Create Date: 2015-11-11 14:43:05.275312

"""

# revision identifiers, used by Alembic.
revision = '43c099bc745'
down_revision = '3e03545a772'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_beam_initiator'), 'beam', ['initiator'], unique=False)
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.drop_constraint('user_email_key', 'user', type_='unique')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('user_email_key', 'user', ['email'])
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_index(op.f('ix_beam_initiator'), table_name='beam')
    ### end Alembic commands ###
