"""empty message

Revision ID: 52b884ded89
Revises: 1229e0b7527
Create Date: 2015-10-04 09:45:13.692340

"""

# revision identifiers, used by Alembic.
revision = '52b884ded89'
down_revision = '1229e0b7527'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('file', sa.Column('last_validated', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_file_last_validated'), 'file', ['last_validated'], unique=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_file_last_validated'), table_name='file')
    op.drop_column('file', 'last_validated')
    ### end Alembic commands ###
