"""empty message

Revision ID: 5aac2f646be
Revises: None
Create Date: 2015-04-08 17:22:52.835421

"""

# revision identifiers, used by Alembic.
revision = '5aac2f646be'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
