"""empty message

Revision ID: 699b7b4a89
Revises: 468931a0788
Create Date: 2015-06-30 14:53:07.185213

"""

# revision identifiers, used by Alembic.
revision = '699b7b4a89'
down_revision = '468931a0788'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_tag_tag'), 'tag', ['tag'], unique=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tag_tag'), table_name='tag')
    ### end Alembic commands ###
