"""empty message

Revision ID: 82b93962abdf
Revises: 3a91facdf84
Create Date: 2016-01-04 14:34:57.642657

"""

# revision identifiers, used by Alembic.
revision = '82b93962abdf'
down_revision = '3a91facdf84'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('beam', sa.Column('comment', sa.String(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('beam', 'comment')
    ### end Alembic commands ###
