"""empty message

Revision ID: 985b368eb54f
Revises: 82b93962abdf
Create Date: 2016-01-27 18:27:23.051001

"""

# revision identifiers, used by Alembic.
revision = '985b368eb54f'
down_revision = '82b93962abdf'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tracker',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('config', sa.String(), nullable=True),
    sa.Column('url', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tracker_name'), 'tracker', ['name'], unique=True)
    op.create_table('issue',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tracker_id', sa.Integer(), nullable=True),
    sa.Column('id_in_tracker', sa.String(), nullable=False),
    sa.Column('open', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['tracker_id'], ['tracker.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tracker_id', 'id_in_tracker', name='uix_unique_issue')
    )
    op.create_index(op.f('ix_issue_tracker_id'), 'issue', ['tracker_id'], unique=False)
    op.create_table('beam_issues',
    sa.Column('beam_id', sa.Integer(), nullable=True),
    sa.Column('issue_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['beam_id'], ['beam.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['issue_id'], ['issue.id'], ondelete='CASCADE')
    )
    op.create_index(op.f('ix_beam_issues_beam_id'), 'beam_issues', ['beam_id'], unique=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_beam_issues_beam_id'), table_name='beam_issues')
    op.drop_table('beam_issues')
    op.drop_index(op.f('ix_issue_tracker_id'), table_name='issue')
    op.drop_table('issue')
    op.drop_index(op.f('ix_tracker_name'), table_name='tracker')
    op.drop_table('tracker')
    ### end Alembic commands ###
