"""empty message

Revision ID: e80348dc45
Revises: 364749445a7
Create Date: 2015-04-22 09:33:17.410752

"""

# revision identifiers, used by Alembic.
revision = 'e80348dc45'
down_revision = '364749445a7'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pin',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('beam_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['beam_id'], ['beam.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('beam_id', 'user_id', name='uix_pin')
    )
    op.add_column('beam', sa.Column('initiator', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'beam', 'user', ['initiator'], ['id'])
    op.add_column('user', sa.Column('name', sa.String(length=255), nullable=True))
    op.drop_column('user', 'confirmed_at')
    op.drop_column('user', 'password')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('password', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('user', sa.Column('confirmed_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_column('user', 'name')
    op.drop_constraint(None, 'beam', type_='foreignkey')
    op.drop_column('beam', 'initiator')
    op.drop_table('pin')
    ### end Alembic commands ###
